### ISSUE TITLE
[FEATURE] Add support for sek II in GradesScreen

### ISSUE THREAD

**Issue by klassenserver7b** [VPlanPlus-Project/VPlanPlus#471]
**Where in the App should the change happen?**
Noten submenu

**What exactly should be changed or added?**
Grade system in Sek II (11/12) is ranged fron 0 to 15.

If you want to calculate the influence of a new grade you can currently only, select 1 to 6 but 0 to 15 would be needed for JG11 and JG12.

Also it would be helpful to filter the grades by school semester because every half of a school year counts on its own.

The Notenbuch app allows this.

![Screenshot_20240411-102740.png](https://github.com/VPlanPlus-Project/VPlanPlus/assets/79657220/cdc78579-7e7a-4c4f-936e-c0d8d5f882c8)

**Comment by Julius-Babies** [comment]
This requires some changes in the internal database as well as modifying the beste.schule repositories. Since your issue covers two features, I'll create another issue in a few days.

Please don't expect this feature in v1.2-stable since it will require some effort. It is planned for v1.3.
